### ISSUE TITLE
Your campaign is currently sending

### ISSUE THREAD

**Issue by nasirkhan** [mettle/sendportal-core#118]
I installed and configured Sendportal as standalone application. I sent some campaigns earlier with 50+ subscribers. Total I tried to send a campaign to around 15K subscribers. I used Tags to select these 15K subscribers. 

It has been about 3 hours and  the campaign status page showing as the following. What can i do to send the remaining subscribers? I faced this issue once in the previous version of sendportal and after that I stopped using the application. The new version have the same issue. How can I debug and fix the issue? 

![Screenshot_2021-03-15 Campaign Status MailPortal](https://user-images.githubusercontent.com/396987/111170537-3ee6c380-85ce-11eb-8055-87cdf048e579.png)

**Comment by JonoB** [comment]
Is there anything relevant in your log files?

**Comment by nasirkhan** [comment]
there are some error in the log similar as "Trying to get property 'subscriber' of non-object ..."

**Comment by nasirkhan** [comment]
It is still showing the following message, Can you please help me to debug the issue, where to find the errors? 

I canceled the previous campaign and tried to send again, but still facing the same issue.

![image](https://user-images.githubusercontent.com/396987/111457572-90b05a80-8742-11eb-8628-62706b971acf.png)

**Comment by HumanG33k** [comment]
My campaign only show 
Your campaign is currently queued
Your campaign is queued and will be sent out soon.

but never send and nothing in logs.

**Comment by nasirkhan** [comment]
@HumanG33k I had the problem once and then found the reason or this. 
You may have not configured the `cron` for the application. Check the laravel doc https://laravel.com/docs/8.x/scheduling#running-the-scheduler to configure the cron. 

to confirm the issue, can you run the command `php artisan schedule:run` and check if the campaign is sending or not?

**Comment by HumanG33k** [comment]
@nasirkhan probably that yes. I didn t remember i read it in the official documentation (for sendportal). Do you know the link ? Or if not exist it should be had.
