### ISSUE TITLE
Campaign status is sent but no mails were sent

### ISSUE THREAD

**Issue by RicardoRamirezR** [mettle/sendportal-core#121]
Hi there,

I do have template and content created.

Any tips?

It worked on v1, I did a fresh install off v2.

BTW, if the campaign is set as SENDING BEHAVIOUR to Queue draft and then each mails send individually the mail is actually sent.

![Captura de Pantalla 2021-04-10 a la(s) 1 14 58 p  m](https://user-images.githubusercontent.com/6526545/114280439-d1785800-99fe-11eb-8b04-74c7d60c2900.png)

About the latest campaign:
![Captura de Pantalla 2021-04-10 a la(s) 1 15 47 p  m](https://user-images.githubusercontent.com/6526545/114280461-f10f8080-99fe-11eb-9044-4026d5a59410.png)

**Comment by JonoB** [comment]
Is your queue worker running?

**Comment by RicardoRamirezR** [comment]
Hi @JonoB,

Yes, it is!
![Captura de Pantalla 2021-04-12 a la(s) 8 20 20 a  m](https://user-images.githubusercontent.com/6526545/114400897-0bb13900-9b68-11eb-903a-22c49a367a80.png)
![Captura de Pantalla 2021-04-12 a la(s) 8 21 30 a  m](https://user-images.githubusercontent.com/6526545/114401046-2aafcb00-9b68-11eb-8089-882e0428fb26.png)

**Comment by RicardoRamirezR** [comment]
Oh my God, I ran horizon manually; then I set horizon via supervisor and is working now!
