### ISSUE TITLE
Add sending limits per hour/day/month for smtp servers

### ISSUE THREAD

**Issue by infabls** [mettle/sendportal-core#123]
Many hosting providers and SMTP servers limit the number of emails to be sent per hour, day. Can you add a setting for SMTP servers so as not to exceed the limit?

Thank you for your hard work on this product

**Comment by b0rt** [comment]
https://github.com/mettle/sendportal-core/pull/128

**Comment by willselby** [comment]
Closing as a duplicate of https://github.com/mettle/sendportal/issues/136
