### ISSUE TITLE
Unknown mailgun error when sending campaign messages

### ISSUE THREAD

**Issue by wzulfikar** [mettle/sendportal-core#134]
Sometimes I get this error when sending email (in production):

![image](https://user-images.githubusercontent.com/7823011/117917630-13f1c500-b31c-11eb-879e-1f912d6ee397.png)

The final error points to this file: /app/vendor/mailgun/mailgun-php/src/Api/HttpApi.php

![image](https://user-images.githubusercontent.com/7823011/117917829-82368780-b31c-11eb-8807-06cc4794cf15.png)

Any hints on how to fix this?

**Comment by JonoB** [comment]
Bit hard for us to debug this. This looks like something on Mailgun's side?
