### ISSUE TITLE
How to enable a translation?

### ISSUE THREAD

**Issue by skinkie** [mettle/sendportal-core#149]
I am using the sendportal git repository, therefore I get sendportal-core import via composer. I notice there is an en.json, after creating an nl.json  and updating sendportal-host.php nl is able to be selected, but I don't see it change in the interface. Maybe this is due to the localization preferences in the browser.

```
diff --git a/config/sendportal-host.php b/config/sendportal-host.php
index df3442b..16733b5 100644
--- a/config/sendportal-host.php
+++ b/config/sendportal-host.php
@@ -12,7 +12,8 @@ return [
     */
     'locale' => [
         'supported' => [
-            'en' => ['name' => 'English', 'native' => 'English']
+            'en' => ['name' => 'English', 'native' => 'English'],
+            'nl' => ['name' => 'Dutch', 'native' => 'Nederlands']
         ]
     ],

```

**Comment by krysits** [comment]
I can not find how to enable my language translation in version 2.0.4 too.

**Comment by JonoB** [comment]
Please see https://laravel.com/docs/10.x/localization#configuring-the-locale

**Comment by skinkie** [comment]
@JonoB these kind of comments really don't help.
