### ISSUE TITLE
Facades to do the CRUD?

### ISSUE THREAD

**Issue by gtu-myowin** [mettle/sendportal-core#158]
First of all, thanks for the nice package. I am trying to do category-base lists (tags). Once user subscribe through the form, they will be added under the tag named after the category they are subscribing to. 

After reading the docs and [this issue](https://github.com/mettle/sendportal/issues/34), I realized that this can only be done through API calls.

But since I am using the package version (Sendportal Core), it feels like I am going around unnecessarily. It would be nice to have the facades and do the CRUD directly. 

Is there any direct ways to do the CRUD?

**Comment by JonoB** [comment]
Yes, just use the repository methods, or even just create your own model calls
