### ISSUE TITLE
Campaign stuck in queue

### ISSUE THREAD

**Issue by techieshark** [mettle/sendportal-core#26]
Hi, thanks for making this & open sourcing it.

I've set up a mailgun-based email service and try to send to my sample list of size 1, and it has been stuck pending in the queue for quite a while (hours).

<img width="514" alt="image" src="https://user-images.githubusercontent.com/1072292/84391264-16472d00-ac3c-11ea-9644-ab55f097e830.png">

Have any ideas on how to debug something not sending?

**Comment by joshuafranks** [comment]
Hey @techieshark, 

If you check out the [Configuration & Setup](https://sendportal.io/docs/getting-started/configuration-and-setup) section of our documentation, you'll notice that we mention Cron Jobs under Additional Configuration. One of the jobs that is run as part of our schedule is the `CampaignDispatchCommand`. This command is responsible for dispatching campaigns and in this case, "queued" means that it's pending the next run of that command (which by default, is every minute). 

If you have not configured a Cron Job or just want to test out campaigns without setting one up, you can run `php artisan sp:campaigns:dispatch`. This will dispatch any campaigns that are waiting in the queue.

**Comment by techieshark** [comment]
Sweet, that did the trick (I also had to make sure the crontab referenced the absolute path for the right version of php on my system.) 

 Thanks @joshuafranks

**Comment by daniel-lucio** [comment]
I have the same issue; however, running artisan won't make the trick.

```
php84 artisan schedule:run

  2025-12-26 03:43:42 Running ['artisan' sp:campaigns:dispatch] ....................................................................... 4s DONE
  ⇂ Dispatch all campaigns waiting in the queue 
```

Please advise
