### ISSUE TITLE
Subscribe Store API Multiple Subs

### ISSUE THREAD

**Issue by daniyals** [mettle/sendportal-core#45]
When I generate the API request to store a new subscriber it generates new subscriber rather checking if the subscriber exists in the system under the workspace and then create it.

Also there is no method available to check if the subscriber exists based on an email being sent.

**Comment by JonoB** [comment]
This has been fixed a while ago: https://github.com/mettle/sendportal-core/commit/aa05b45e3dcf88b55addc6df7267729b82c5857c
