### ISSUE TITLE
how to setup

### ISSUE THREAD

**Issue by nagaraj32** [mettle/sendportal-core#96]
can please hepl on how to setup .....prepare any videos quick setup

thanks

**Comment by JonoB** [comment]
Please see sendportal.io/docs

**Comment by nagaraj32** [comment]
can please share source code....quick implement

**Comment by nagaraj32** [comment]
composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - laravel/horizon is locked to version v4.3.5 and an update of this package was not requested.
    - laravel/horizon v4.3.5 requires ext-pcntl * -> it is missing from your system. Install or enable PHP's pcntl extension.
